### ISSUE TITLE
[API] Les routes particulières aux admin

### ISSUE THREAD

**Issue by samchery** [HETIC-W3-G12/node-api#49]
## Todo

- [x] liste des offres 
> GET /admin/offers

- [x] liste des projets et utilisateurs associés
> GET /admin/projects

- [x] valider un projet donné
> GET /admin/projects/valid/:id

- [x] liste des utilisateurs
/admin/users

- [x] nombre d'utilisateurs
/admin/users/count
